const GET_BOOKS = 'GET_BOOKS';
const SET_BOOKS = 'SET_BOOKS';
const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
const STORE_QUERY = 'STORE_QUERY';
const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_TOTAL_PAGES = 'Set_TOTAL_PAGES';
const SET_LOADING_STATE = 'SET_LOADING_STATE';
const CLEAR_SEARCH = 'CLEAR_SEARCH';
const UPDATE_LOCATION = 'UPDATE_LOCATION';
const GET_SUGGESTIONS = 'GET_SUGGESTIONS';
const SET_SUGGESTIONS = 'SET_SUGGESTIONS';
const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';

export {  //eslint-disable-line
  GET_BOOKS,
  SET_BOOKS,
  ADD_TO_WISHLIST,
  REMOVE_FROM_WISHLIST,
  STORE_QUERY,
  SET_SEARCH_TYPE,
  SET_CURRENT_PAGE,
  SET_TOTAL_PAGES,
  SET_LOADING_STATE,
  CLEAR_SEARCH,
  UPDATE_LOCATION,
  GET_SUGGESTIONS,
  SET_SUGGESTIONS,
  CLEAR_SUGGESTIONS,
};